package com.youmai.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.youmai.db.bean.ChargerBean;
import com.youmai.db.bean.PriceBean;

import com.youmai.db.dao.ChargerBeanDao;
import com.youmai.db.dao.PriceBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chargerBeanDaoConfig;
    private final DaoConfig priceBeanDaoConfig;

    private final ChargerBeanDao chargerBeanDao;
    private final PriceBeanDao priceBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chargerBeanDaoConfig = daoConfigMap.get(ChargerBeanDao.class).clone();
        chargerBeanDaoConfig.initIdentityScope(type);

        priceBeanDaoConfig = daoConfigMap.get(PriceBeanDao.class).clone();
        priceBeanDaoConfig.initIdentityScope(type);

        chargerBeanDao = new ChargerBeanDao(chargerBeanDaoConfig, this);
        priceBeanDao = new PriceBeanDao(priceBeanDaoConfig, this);

        registerDao(ChargerBean.class, chargerBeanDao);
        registerDao(PriceBean.class, priceBeanDao);
    }
    
    public void clear() {
        chargerBeanDaoConfig.clearIdentityScope();
        priceBeanDaoConfig.clearIdentityScope();
    }

    public ChargerBeanDao getChargerBeanDao() {
        return chargerBeanDao;
    }

    public PriceBeanDao getPriceBeanDao() {
        return priceBeanDao;
    }

}
